FROM python:3.9.0

COPY python-requirements.txt python-requirements.txt
RUN pip install --upgrade pip
RUN pip install -r python-requirements.txt

ADD . /app
WORKDIR /app

ENV FLASK_ENV=development
ENV FLASK_APP=__init__.py

CMD flask run --host=0.0.0.0